services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: skill_app
    volumes:
      - .:/var/www/html
      - storage_data:/var/www/html/storage
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    container_name: skill_nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  postgres:
    image: postgres:16-alpine
    container_name: skill_postgres
    environment:
      POSTGRES_DB: skill_platform
      POSTGRES_USER: skill_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: skill_redis

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: skill_queue
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    volumes:
      - .:/var/www/html
      - storage_data:/var/www/html/storage
    depends_on:
      - app
      - postgres
      - redis

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: skill_scheduler
    command: php artisan schedule:work
    volumes:
      - .:/var/www/html
      - storage_data:/var/www/html/storage
    depends_on:
      - app
      - postgres
      - redis

volumes:
  postgres_data:
  storage_data:
